In [1]:
import os
import h5py
import json
import pandas as pd

/home/jackalhan/Development/github/bilm-tf/venv/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
import tensorflow as tf

In [15]:
#a = tf.constant([[100, 110], [10, 20], [1000, 1100]])
a = tf.random_uniform(shape=[3, 150,1024])

In [26]:
b = tf.reduce_mean(a)
c = tf.reduce_mean(a, axis=0)
d = tf.reduce_mean(a, axis=1)
e = tf.reduce_mean(a, axis=2)
f = tf.reduce_mean(a, axis=[0,1])

In [27]:
session = tf.Session()

In [28]:
print("INPUT")
print(session.run(a))
print("REDUCE MEAN")
print(session.run(b))
print("REDUCE MEAN (shape)")
print(b.shape)
print("REDUCE MEAN AXIS 0")
print(session.run(c))
print("REDUCE MEAN AXIS 0 (shape)")
print(c.shape)
print("REDUCE MEAN AXIS 1")
print(session.run(d))
print("REDUCE MEAN AXIS 1 (shape)")
print(d.shape)
print("REDUCE MEAN AXIS 2")
print(session.run(e))
print("REDUCE MEAN AXIS 2 (shape)")
print(e.shape)
print("REDUCE MEAN AXIS 0,1")
print(session.run(f))
print("REDUCE MEAN AXIS 0,1 (shape)")
print(f.shape)

INPUT
[[[0.14361286 0.74463546 0.05528474 ... 0.42196012 0.83750486 0.32525635]
  [0.8512775  0.40255404 0.6226797  ... 0.9696106  0.5934336  0.24274111]
  [0.29692662 0.8753855  0.28486526 ... 0.33133066 0.5703893  0.58597136]
  ...
  [0.29707527 0.51404476 0.9240384  ... 0.34801102 0.2070018  0.25367928]
  [0.78632    0.36166894 0.41988075 ... 0.8387991  0.7794237  0.6020839 ]
  [0.13407731 0.9202765  0.29769742 ... 0.3187636  0.06853759 0.86523616]]

 [[0.7800853  0.72759056 0.7789978  ... 0.67362404 0.9373268  0.42324948]
  [0.37501156 0.8671254  0.78329694 ... 0.5555297  0.54702055 0.6134634 ]
  [0.96783996 0.40766132 0.52161574 ... 0.35092616 0.90680766 0.9696127 ]
  ...
  [0.41031122 0.18462563 0.9901916  ... 0.69740224 0.1939987  0.6404489 ]
  [0.8943119  0.26174676 0.8990778  ... 0.17971289 0.2937343  0.3150028 ]
  [0.16068578 0.6621947  0.736832   ... 0.26410758 0.33290815 0.64911294]]

 [[0.02733278 0.7306404  0.77339077 ... 0.8486546  0.28127265 0.78303254]
  [0.50643885 0.

In [2]:
#dataset_type = 'train'
dataset_type = 'dev'
dataset_version = 'v1.1'

index_field = ['Unnamed: 0']

# required files
_basepath = '/home/jackalhan/Development/github/bilm-tf/squad'
datadir = os.path.join(_basepath, dataset_type)
modeldir = os.path.join(_basepath, 'model')

In [ ]:

filename = 'file.hdf5'
f = h5py.File(filename, 'r')

# List all groups
print("Keys: %s" % f.keys())
a_group_key = list(f.keys())[0]

# Get the data
data = list(f[a_group_key])

In [ ]:
paragraphs_with_mean = []
questions_with_mean = []
items = [dict({'type':'question', 
                     'list':questions_with_mean, 
                     'source_file':embedding_question_file_as_h5py,
                     'destination_file': embedding_mean_question_file_as_h5py}), 
              dict({'type':'paragraph', 
                     'list':paragraphs_with_mean, 
                     'source_file':embedding_paragraph_file_as_h5py,
                     'destination_file': embedding_mean_paragraph_file_as_h5py})
              ]
for vals in items:
    print(vals['type'], 'is getting processed!!!')
    config = tf.ConfigProto(allow_soft_placement=True)
    
    with h5py.File(vals['source_file'], 'r') as fin:
        data_as_array = np.array(fin)
    
    print(data_as_array.shape)
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())
         h5py.File(vals['destination_file'], 'w') as fout:
            #for _ in tqdm_notebook(fin, total=len(fin)):
                mean_vectors = sess.run(tf.reduce_mean(fin[str(_)][...], axis=[0,1]))
                
                data_as_array
                x = tf.placeholder(tf.float32, [100, 250])
                norm = tf.sqrt(tf.reduce_sum(tf.square(x), 1, keep_dims=True))
                res = x / norm
                vals['list'].append(mean_vector)
                ds = fout.create_dataset(
                        '{}'.format(_),
                        mean_vector.shape, dtype='float32',
                        data=mean_vector)