In [1]:
import h5py
import numpy as np
import os
import pandas as pd
from tqdm import tqdm
import sys
path = !echo ${VIRTUAL_ENV}
path = os.path.join(path[0], '..')
sys.path.append(path)
import helper.utils as UTIL

/home/jackalhan/Development/github/more_meaningful_representations/venv35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
DIR = '/media/jackalhan/Samsung_T5/Rethinking_Running_Data_QUASAR-T_short'
args={
'train_word_embeddings': 'train_word_embeddings.txt',
'dev_word_embeddings': 'dev_word_embeddings.txt',
'train_question_labels': 'train_question_labels.csv',
'dev_question_labels': 'dev_question_labels.csv',
'train_dataset_file': 'train.json',
'dev_dataset_file': 'dev.json',
    
'train_paragraph_embeddings': 'train_paragraph_embeddings.hdf5',
'train_question_embeddings': 'train_question_embeddings.hdf5',
'dev_paragraph_embeddings': 'dev_paragraph_embeddings.hdf5',
'dev_question_embeddings': 'dev_question_embeddings.hdf5',

'ultimate_paragraph_embeddings': 'paragraph_embeddings.hdf5',
'ultimate_question_embeddings': 'question_embeddings.hdf5',
'ultimate_dataset_question_file': 'dataset_question_file.txt',
'ultimate_dataset_paragraph_file': 'dataset_paragraph_file.txt',
'ultimate_question_labels': 'question_labels.csv',
'ultimate_word_embeddings': 'ultimate_word_embeddings.txt'
}

## DATASET FILE

In [5]:
dev_tokenized_questions, \
dev_tokenized_paragraphs,\
dev_questions_nontokenized,\
dev_paragraphs_nontokenized = UTIL.prepare_squad_objects(os.path.join(DIR, args['dev_dataset_file']), 'DEV', 
                                                         is_dump_during_execution=True,
                                                         mapping_file=os.path.join(DIR, args['dev_question_labels']))

print('Len of Dev Questions: {}, Len of Dev Paragraphs: {}'.format(len(dev_tokenized_questions),
                                                                  len(dev_tokenized_paragraphs)))

train_tokenized_questions, \
train_tokenized_paragraphs,\
train_questions_nontokenized,\
train_paragraphs_nontokenized = UTIL.prepare_squad_objects(os.path.join(DIR, args['train_dataset_file']), 'TRAIN',
                                                          is_dump_during_execution=True,
                                                         mapping_file=os.path.join(DIR, args['train_question_labels']))
print('Len of Train Questions: {}, Len of Train Paragraphs: {}'.format(len(train_tokenized_questions),
                                                                  len(train_tokenized_paragraphs)))


# ultimate_tokenized_questions = dev_tokenized_questions + train_tokenized_questions
# ultimate_tokenized_paragraphs = dev_tokenized_paragraphs + train_tokenized_paragraphs
# ultimate_questions_nontokenized = dev_questions_nontokenized + train_questions_nontokenized
# ultimate_paragraphs_nontokenized = dev_paragraphs_nontokenized + train_paragraphs_nontokenized
# print('Len of Ultimate Questions: {}, Len of Ultimate Paragraphs: {}'.format(len(ultimate_tokenized_questions),
#                                                                   len(ultimate_tokenized_paragraphs)))

# #QUESTION LABELS #

# dev_question_labels = pd.read_csv(os.path.join(DIR, args['dev_question_labels']))
# print(dev_question_labels.shape)
# train_question_labels = pd.read_csv(os.path.join(DIR, args['train_question_labels']))
# print(train_question_labels.shape)
# #concate all dfs 
# frames = [dev_question_labels, train_question_labels]
# ultimate_question_labels = pd.concat(frames, ignore_index=True)
# del dev_question_labels, train_question_labels,frames
# ultimate_question_labels.reset_index()
# print(ultimate_question_labels.shape)


# ultimate_question_labels.loc[ultimate_question_labels.index >= 10570, ['p'] ] = ultimate_question_labels + len(dev_tokenized_paragraphs)
# ultimate_question_labels.loc[ultimate_question_labels.index >= 10570, ['q'] ] = ultimate_question_labels + len(dev_tokenized_questions)

# #ultimate_question_labels[ultimate_question_labels.index >= 0]
# ultimate_question_labels.to_csv(os.path.join(DIR, args['ultimate_question_labels']), index=False)


# # DATASET FILES #

# with open(os.path.join(DIR, args['ultimate_dataset_question_file']), 'w') as fout:
#     for sentence in ultimate_tokenized_questions:
#         cleaned_sentence = [word.replace('\n', ' ') for word in sentence]
#         fout.write(' '.join(cleaned_sentence) + '\n')

# with open(os.path.join(DIR, args['ultimate_dataset_paragraph_file']), 'w') as fout:
#     for sentence in ultimate_tokenized_paragraphs:
#         cleaned_sentence = [word.replace('\n', ' ') for word in sentence]
#         fout.write(' '.join(cleaned_sentence) + '\n')

# # DOCUMENT EMBEDDINGS #

# dev_question_embeddings = UTIL.load_embeddings(os.path.join(DIR, args['dev_question_embeddings']))
# print(dev_question_embeddings.shape)
# train_question_embeddings = UTIL.load_embeddings(os.path.join(DIR, args['train_question_embeddings']))
# print(train_question_embeddings.shape)
# ultimate_question_embeddings = np.vstack((dev_question_embeddings, train_question_embeddings))
# print(ultimate_question_embeddings.shape)

# dev_paragraph_embeddings = UTIL.load_embeddings(os.path.join(DIR, args['dev_paragraph_embeddings']))
# print(dev_paragraph_embeddings.shape)
# train_paragraph_embeddings = UTIL.load_embeddings(os.path.join(DIR, args['train_paragraph_embeddings']))
# print(train_paragraph_embeddings.shape)
# ultimate_paragraph_embeddings = np.vstack((dev_paragraph_embeddings, train_paragraph_embeddings))
# print(ultimate_paragraph_embeddings.shape)

# UTIL.dump_embeddings(ultimate_question_embeddings, os.path.join(DIR, args['ultimate_question_embeddings']))
# UTIL.dump_embeddings(ultimate_paragraph_embeddings, os.path.join(DIR, args['ultimate_paragraph_embeddings']))

  8%|▊         | 238/3000 [00:00<00:01, 2375.22it/s]

****************************************************************************************************
Parsing Started
Generating DEV examples...


100%|██████████| 3000/3000 [00:01<00:00, 1871.77it/s]


3000 questions in total
# of Paragraphs in DEV : 3000
# of Questions in DEV : 3000
# of Q_to_P DEV : 3000
--------------------
Paragraphs: Tokenization and Saving Tokenization Started in DEV
# of Tokenized Paragraphs in DEV : 3000
--------------------
Questions: Tokenization and Saving Tokenization Started in DEV
# of Tokenized Questions in DEV : 3000
Mapping data is dumped to /media/jackalhan/Samsung_T5/Rethinking_Running_Data_QUASAR-T_short/dev_question_labels.csv
Parsing Ended in 0.03333333333333333 minutes
****************************************************************************************************
Len of Dev Questions: 3000, Len of Dev Paragraphs: 3000
****************************************************************************************************
Parsing Started
Generating TRAIN examples...


100%|██████████| 37012/37012 [00:22<00:00, 1639.79it/s]


37012 questions in total
# of Paragraphs in TRAIN : 37012
# of Questions in TRAIN : 37012
# of Q_to_P TRAIN : 37012
--------------------
Paragraphs: Tokenization and Saving Tokenization Started in TRAIN
# of Tokenized Paragraphs in TRAIN : 37012
--------------------
Questions: Tokenization and Saving Tokenization Started in TRAIN
# of Tokenized Questions in TRAIN : 37012
Mapping data is dumped to /media/jackalhan/Samsung_T5/Rethinking_Running_Data_QUASAR-T_short/train_question_labels.csv
Parsing Ended in 0.6333333333333333 minutes
****************************************************************************************************
Len of Train Questions: 37012, Len of Train Paragraphs: 37012


## WORD EMBEDDINGS (Run 2 times, one for NOIDF, other one for WITHIDF)

In [330]:
dev_word_embeddings = {}
with open(os.path.join(DIR, args['dev_word_embeddings']), 'r', encoding='utf-8') as f:
    for line in f:
        values = line.strip().split()
        w = values[0]
        vectors = np.asarray(values[1:], dtype='float32')
        dev_word_embeddings[w] = vectors

train_word_embeddings = {}
with open(os.path.join(DIR, args['train_word_embeddings']), 'r', encoding='utf-8') as f:
    for line in f:
        values = line.strip().split()
        w = values[0]
        vectors = np.asarray(values[1:], dtype='float32')
        train_word_embeddings[w] = vectors

In [331]:
ultimate_word_embeddings = {}
for w, v in train_word_embeddings.items():
    if w not in ultimate_word_embeddings:
        ultimate_word_embeddings[w] = v

for w, v in dev_word_embeddings.items():
    if w not in ultimate_word_embeddings:
        ultimate_word_embeddings[w] = v   

In [332]:
dev_word_embeddings['Which']

array([-0.7793356 , -2.3099442 , -0.5907096 , ...,  0.84358245,
        0.05804019, -0.5466166 ], dtype=float32)

In [333]:
with open(os.path.join(DIR, args['ultimate_word_embeddings']), 'w') as fout:
    for w, v in ultimate_word_embeddings.items():
        data = ' '.join(map(str, v))
        fout.write(w + ' ' + data)
        fout.write("\n")

In [334]:
print(ultimate_word_embeddings['Which'])
print(ultimate_word_embeddings['which'])

[-0.7793356  -2.3099442  -0.5907096  ...  0.84358245  0.05804019
 -0.5466166 ]
[ 0.16745289 -0.9450648  -0.25376654 ...  0.8265831   0.31300718
 -0.47571355]


In [335]:
testing_ultimate_word_embeddings = {}
with open(os.path.join(DIR, args['ultimate_word_embeddings']), 'r', encoding='utf-8') as f:
    for line in f:
        values = line.strip().split()
        w = values[0]
        vectors = np.asarray(values[1:], dtype='float32')
        testing_ultimate_word_embeddings[w] = vectors

In [336]:
print(testing_ultimate_word_embeddings['Which'])
print(testing_ultimate_word_embeddings['which'])

[-0.7793356  -2.3099442  -0.5907096  ...  0.84358245  0.05804019
 -0.5466166 ]
[ 0.16745289 -0.9450648  -0.25376654 ...  0.8265831   0.31300718
 -0.47571355]


In [286]:
from sklearn import preprocessing
X_squared = test_word ** 2
X_sum_squared = np.sum([X_squared], axis=1)
X_sum_squared

array([23.29759], dtype=float32)

In [34]:
dev_tokenized_questions, \
dev_tokenized_paragraphs,\
dev_questions_nontokenized,\
dev_paragraphs_nontokenized = UTIL.prepare_squad_objects(os.path.join(DIR, args['dev_dataset_file']), 'DEV')

print('Len of Dev Questions: {}, Len of Dev Paragraphs: {}'.format(len(dev_tokenized_questions),
                                                                  len(dev_tokenized_paragraphs)))

train_tokenized_questions, \
train_tokenized_paragraphs,\
train_questions_nontokenized,\
train_paragraphs_nontokenized = UTIL.prepare_squad_objects(os.path.join(DIR, args['train_dataset_file']), 'TRAIN')
print('Len of Train Questions: {}, Len of Train Paragraphs: {}'.format(len(train_tokenized_questions),
                                                                  len(train_tokenized_paragraphs)))



  0%|          | 0/48 [00:00<?, ?it/s]

****************************************************************************************************
Parsing Started
Generating DEV examples...


100%|██████████| 48/48 [00:06<00:00,  7.23it/s]


10570 questions in total
# of Paragraphs in DEV : 2067
# of Questions in DEV : 10570
# of Q_to_P DEV : 10570
--------------------
Paragraphs: Tokenization and Saving Tokenization Started in DEV
# of Tokenized Paragraphs in DEV : 2067
--------------------
Questions: Tokenization and Saving Tokenization Started in DEV
# of Tokenized Questions in DEV : 10570
Parsing Ended in 0.18333333333333332 minutes
****************************************************************************************************
Len of Dev Questions: 10570, Len of Dev Paragraphs: 2067
****************************************************************************************************
Parsing Started
Generating TRAIN examples...


100%|██████████| 442/442 [01:02<00:00,  7.06it/s]


87599 questions in total
# of Paragraphs in TRAIN : 18896
# of Questions in TRAIN : 87599
# of Q_to_P TRAIN : 87599
--------------------
Paragraphs: Tokenization and Saving Tokenization Started in TRAIN
# of Tokenized Paragraphs in TRAIN : 18896
--------------------
Questions: Tokenization and Saving Tokenization Started in TRAIN
# of Tokenized Questions in TRAIN : 87599
Parsing Ended in 1.7666666666666666 minutes
****************************************************************************************************
Len of Train Questions: 87599, Len of Train Paragraphs: 18896


In [35]:
# PARAGRAPHS ARE GETTING LOADED
paragraph_embeddings = UTIL.load_embeddings(os.path.join(DIR,
                                                    args['paragraph_embeddings']))

# TRAIN QUESTIONS ARE GETTING LOADED
train_question_indx = UTIL.load_embeddings(os.path.join(DIR,
                                                        args['train_question_indx']))
train_question_indx = train_question_indx.astype(int)

train_question_label_indx = UTIL.load_embeddings(os.path.join(DIR,
                                                         args['train_question_label_indx']))
train_question_label_indx = train_question_label_indx.astype(int)

In [11]:
train_question_labels = None
for label_indx in tqdm(train_question_label_indx):
    train_question_label = paragraph_embeddings[label_indx, :]
    if train_question_labels is None:
        train_question_labels = train_question_label
    else:
        train_question_labels = np.vstack((train_question_labels, train_question_label))

100%|██████████| 84787/84787 [43:25<00:00, 32.54it/s] 


In [36]:
tokenized_questions = dev_tokenized_questions + train_tokenized_questions
tokenized_paragraphs = dev_tokenized_paragraphs + train_tokenized_paragraphs
questions_nontokenized = dev_questions_nontokenized + train_questions_nontokenized
paragraphs_nontokenized = dev_paragraphs_nontokenized + train_paragraphs_nontokenized


In [14]:
train_questions = []
for indx in tqdm(train_question_indx):
    train_question = questions_nontokenized[indx]
    train_questions.append(train_question)

100%|██████████| 84787/84787 [00:00<00:00, 1211949.88it/s]


In [37]:
train_tokenized_questions = [question.split(' ') for question in train_questions]

NameError: name 'train_questions' is not defined

In [17]:
indx_to_voc, voc_to_indx = UTIL.vocabulary_processor(tokenized_questions)

45425 vocs are created


In [19]:
train_tokenized_questions = UTIL.fit_vocab_to_documents(train_tokenized_questions, voc_to_indx)

In [21]:
from tensorflow.python.keras.preprocessing import sequence

In [22]:
x_train = sequence.pad_sequences(train_tokenized_questions,
                             maxlen=args['max_document_len'],
                             truncating='post',
                             padding='post',
                             value=0)

In [24]:
UTIL.save_as_pickle(x_train, os.path.join(DIR, 'x_train.pkl'))

In [25]:
UTIL.save_as_pickle(voc_to_indx, os.path.join(DIR, 'voc_to_indx.pkl'))

In [27]:
valid_question_indx = UTIL.load_embeddings(os.path.join(DIR,
                                                        args['valid_question_indx']))
valid_question_indx = valid_question_indx.astype(int)

valid_question_label_indx = UTIL.load_embeddings(os.path.join(DIR,
                                                        args['valid_question_label_indx']))
valid_question_label_indx = valid_question_label_indx.astype(int)


In [28]:
valid_question_labels = None
for label_indx in tqdm(valid_question_label_indx):
    valid_question_label = paragraph_embeddings[label_indx, :]
    if valid_question_labels is None:
        valid_question_labels = valid_question_label
    else:
        valid_question_labels = np.vstack((valid_question_labels, valid_question_label))

valid_questions = []
for indx in tqdm(valid_question_indx):
    valid_question = questions_nontokenized[indx]
    valid_questions.append(valid_question)

100%|██████████| 5000/5000 [00:00<00:00, 1279843.77it/s]


In [29]:
valid_tokenized_questions = [question.split(' ') for question in valid_questions]

In [30]:
valid_tokenized_questions = UTIL.fit_vocab_to_documents(valid_tokenized_questions, voc_to_indx)

In [32]:
x_valid = sequence.pad_sequences(valid_tokenized_questions,
                                 maxlen=args['max_document_len'],
                                 truncating='post',
                                 padding='post',
                                 value=0)

In [33]:
UTIL.save_as_pickle(x_valid, os.path.join(DIR, 'x_valid.pkl'))

In [34]:
train_question_labels[0]

array([-0.2607108 ,  0.37758777,  0.3615227 , ..., -0.1298241 ,
        0.46128392, -0.08047347], dtype=float32)

In [35]:
x_valid.shape

(5000, 130)

## TASK1: IF VOC ALREADY EXIST

In [98]:
TASK_1_DIR = '/home/jackalhan/Development/github/more_meaningful_representations/squad/train/improvement/data/'
#TASK_1_DIR = os.path.join(DIR, 'ULTIMATE_OLD_API_with_IDF_with_1_0_0')

In [99]:
args={
'train_dataset_file': 'train-v1.1.json',
'dev_dataset_file': 'dev-v1.1.json',

'max_document_len': 130,
'paragraph_embeddings': 'recall_paragraph_embeddings.hdf5',
'train_recall_question_indx': 'train_recall_question_5000_idx.hdf5',
'train_recall_label_indx': 'train_recall_question_5000_labels.hdf5'
}

In [100]:
dev_tokenized_questions, \
dev_tokenized_paragraphs,\
dev_questions_nontokenized,\
dev_paragraphs_nontokenized = UTIL.prepare_squad_objects(os.path.join(TASK_1_DIR, args['dev_dataset_file']), 'DEV')

print('Len of Dev Questions: {}, Len of Dev Paragraphs: {}'.format(len(dev_tokenized_questions),
                                                                  len(dev_tokenized_paragraphs)))

train_tokenized_questions, \
train_tokenized_paragraphs,\
train_questions_nontokenized,\
train_paragraphs_nontokenized = UTIL.prepare_squad_objects(os.path.join(TASK_1_DIR, args['train_dataset_file']), 'TRAIN')
print('Len of Train Questions: {}, Len of Train Paragraphs: {}'.format(len(train_tokenized_questions),
                                                                  len(train_tokenized_paragraphs)))



  2%|▏         | 1/48 [00:00<00:05,  7.92it/s]

****************************************************************************************************
Parsing Started
Generating DEV examples...


100%|██████████| 48/48 [00:06<00:00,  6.93it/s]


10570 questions in total
# of Paragraphs in DEV : 2067
# of Questions in DEV : 10570
# of Q_to_P DEV : 10570
--------------------
Paragraphs: Tokenization and Saving Tokenization Started in DEV
# of Tokenized Paragraphs in DEV : 2067
--------------------
Questions: Tokenization and Saving Tokenization Started in DEV
# of Tokenized Questions in DEV : 10570
Parsing Ended in 0.18333333333333332 minutes
****************************************************************************************************
Len of Dev Questions: 10570, Len of Dev Paragraphs: 2067
****************************************************************************************************

100%|██████████| 442/442 [01:02<00:00,  7.03it/s]



Parsing Started
Generating TRAIN examples...
87599 questions in total
# of Paragraphs in TRAIN : 18896
# of Questions in TRAIN : 87599
# of Q_to_P TRAIN : 87599
--------------------
Paragraphs: Tokenization and Saving Tokenization Started in TRAIN
# of Tokenized Paragraphs in TRAIN : 18896
--------------------
Questions: Tokenization and Saving Tokenization Started in TRAIN
# of Tokenized Questions in TRAIN : 87599
Parsing Ended in 1.7666666666666666 minutes
****************************************************************************************************
Len of Train Questions: 87599, Len of Train Paragraphs: 18896


In [101]:
tokenized_questions = dev_tokenized_questions + train_tokenized_questions
tokenized_paragraphs = dev_tokenized_paragraphs + train_tokenized_paragraphs
questions_nontokenized = dev_questions_nontokenized + train_questions_nontokenized
paragraphs_nontokenized = dev_paragraphs_nontokenized + train_paragraphs_nontokenized


In [102]:
voc_to_indx = UTIL.load_from_pickle(os.path.join(TASK_1_DIR, 'voc_to_indx.pkl'))

In [103]:
len(voc_to_indx)

45425

In [106]:
# PARAGRAPHS ARE GETTING LOADED
paragraph_embeddings = UTIL.load_embeddings(os.path.join(TASK_1_DIR,
                                                    args['paragraph_embeddings']))

In [105]:
train_recall_question_indx = UTIL.load_embeddings(os.path.join(TASK_1_DIR,
                                                        args['train_recall_question_indx']))
train_recall_question_indx = train_recall_question_indx.astype(int)

train_recall_question_label_indx = UTIL.load_embeddings(os.path.join(TASK_1_DIR,
                                                        args['train_recall_label_indx']))
train_recall_question_label_indx = train_recall_question_label_indx.astype(int)


In [107]:
train_recall_question_labels = None
for label_indx in tqdm(train_recall_question_label_indx):
    train_recall_question_label = paragraph_embeddings[label_indx, :]
    if train_recall_question_labels is None:
        train_recall_question_labels = train_recall_question_label
    else:
        train_recall_question_labels = np.vstack((train_recall_question_labels, train_recall_question_label))

train_recall_questions = []
for indx in tqdm(train_recall_question_indx):
    train_recall_question = questions_nontokenized[indx]
    train_recall_questions.append(train_recall_question)

100%|██████████| 5000/5000 [00:00<00:00, 1354749.35it/s]


In [109]:
train_recall_tokenized_questions = [question.split(' ') for question in train_recall_questions]

In [111]:
train_recall_tokenized_questions[1]

['In', 'what', 'year', 'did', 'Bermuda', 'enter', 'British', 'rule', '?']

In [114]:
train_recall_tokenized_questions = UTIL.fit_vocab_to_documents(train_recall_tokenized_questions, voc_to_indx)

In [116]:
train_recall_tokenized_questions[1]

[236, 46, 54, 14, 33127, 982, 1087, 1592, 11]

In [117]:
voc_to_indx['In']

236

In [118]:
x_train_recall = sequence.pad_sequences(train_recall_tokenized_questions,
                                 maxlen=args['max_document_len'],
                                 truncating='post',
                                 padding='post',
                                 value=0)

In [121]:
x_train_recall

array([[  245,    14,   869, ...,     0,     0,     0],
       [  236,    46,    54, ...,     0,     0,     0],
       [   18,   336,    58, ...,     0,     0,     0],
       ...,
       [   37,    20, 34508, ...,     0,     0,     0],
       [  236,    46,  6636, ...,     0,     0,     0],
       [   18,    32,     5, ...,     0,     0,     0]], dtype=int32)

In [120]:
UTIL.save_as_pickle(x_train_recall, os.path.join(TASK_1_DIR, 'x_train_valid.pkl'))

## TASK2: CONVERT QUESTION_LABELS. HDF5 to CSV

In [122]:
TASK_2_DIR = '/home/jackalhan/Development/github/more_meaningful_representations/squad/train/improvement/data/ULTIMATE_OLD_API_with_1_0_0'
labels_as_h5py_file_name = 'train_question_labels.hdf5'
labels_as_h5py_file = os.path.join(TASK_2_DIR, labels_as_h5py_file_name)

In [5]:
labels_as_h5py = UTIL.load_embeddings(labels_as_h5py_file)

In [6]:
labels_as_h5py = labels_as_h5py.astype(int)

In [11]:
pd.DataFrame(labels_as_h5py, columns=['p']).to_csv(os.path.join(TASK_2_DIR, 'question_labels.csv'))

## TASK3: L2 CHECK

In [248]:
TASK_3_DIR = '/home/jackalhan/Development/github/more_meaningful_representations/squad/dev/ELMO_CONTEXT_OLD_API_EMBEDDINGS'
h5py_file_name1 = 'dev_token_embeddings_old_api_doc_0.hdf5'
h5py_file_name2 = 'dev_token_embeddings_old_api_doc_1.hdf5'
h5py_file1 = UTIL.load_embeddings(os.path.join(TASK_3_DIR, h5py_file_name1))
h5py_file2 = UTIL.load_embeddings(os.path.join(TASK_3_DIR, h5py_file_name2))
h5py_file3 = UTIL.load_embeddings('/media/jackalhan/Extreme 500/ULTIMATE_OLD_API_with_1_0_0_L2/dev_question_embeddings.hdf5')

In [185]:
h5py_file = np.vstack((h5py_file1, h5py_file2))

In [186]:
from sklearn import preprocessing

In [188]:
h5py_file.shape

(22, 3, 1024)

In [189]:
h5py_file[:,0,:]

array([[-0.7793356 , -2.3099442 , -0.5907096 , ...,  0.84358245,
         0.05804019, -0.5466166 ],
       [ 0.7555715 , -0.37882742,  0.10019857, ...,  0.45271248,
        -0.03817607, -0.68883264],
       [ 0.31546307, -0.14667389, -0.27995116, ..., -0.08131212,
         0.32476687, -0.18639295],
       ...,
       [ 0.10457286,  0.3696899 , -1.2471359 , ..., -0.12930577,
        -0.02476517, -0.06765284],
       [-0.24508505,  0.28492582, -0.29489422, ...,  0.16593422,
        -1.1265616 , -0.21003507],
       [-1.1727259 ,  0.22724494, -1.5357871 , ...,  1.0646051 ,
         0.27659285,  0.7338671 ]], dtype=float32)

In [179]:
x = h5py_file[0,1,:]
x = np.reshape(x, (1,1,-1))

In [183]:
x.shape

(1, 1, 1024)

In [192]:
x.shape

(1, 1, 1024)

In [249]:
h5py_file3

array([[-0.00038471, -0.00580528, -0.01100152, ...,  0.01517917,
         0.00184055, -0.00921226],
       [-0.00013369, -0.00914192, -0.01381616, ...,  0.0171214 ,
         0.0003133 , -0.00878628],
       [ 0.01117491, -0.01330363,  0.00180931, ...,  0.00488911,
        -0.00469446,  0.00674144],
       ...,
       [ 0.00914114,  0.00754567, -0.01404146, ..., -0.00160104,
         0.0135705 ,  0.00185585],
       [ 0.00043095, -0.00216133, -0.00534114, ...,  0.00170421,
         0.00086083, -0.01188126],
       [-0.00669443,  0.00216011,  0.00088808, ...,  0.00402101,
         0.01271245, -0.00432279]], dtype=float32)

In [250]:
X_normalized = preprocessing.normalize(h5py_file3, norm='l2')

In [251]:
X_normalized

array([[-0.00113517, -0.01712958, -0.03246208, ...,  0.04478905,
         0.00543091, -0.02718254],
       [-0.0003949 , -0.02700318, -0.04080984, ...,  0.05057276,
         0.00092542, -0.02595271],
       [ 0.03100294, -0.03690875,  0.00501963, ...,  0.01356402,
        -0.01302401,  0.01870303],
       ...,
       [ 0.03508054,  0.02895767, -0.0538863 , ..., -0.00614423,
         0.05207889,  0.00712211],
       [ 0.00152789, -0.00766276, -0.01893638, ...,  0.00604208,
         0.00305197, -0.04212362],
       [-0.02563315,  0.00827113,  0.00340048, ...,  0.01539655,
         0.0486763 , -0.01655209]], dtype=float32)

In [252]:
X_squared = X_normalized ** 2

In [253]:
X_sum_squared = np.sum(X_squared, axis=1)

In [254]:
X_sum_squared

array([1.        , 0.99999994, 0.9999999 , ..., 0.99999994, 0.9999998 ,
       1.        ], dtype=float32)

In [255]:
X_squared = h5py_file3 ** 2
X_squared.shape

(10570, 1024)

In [256]:
X_sum_squared = np.sum(X_squared, axis=1)

In [257]:
X_sum_squared

array([0.11485567, 0.11461592, 0.12992178, ..., 0.06789973, 0.07955605,
       0.06820612], dtype=float32)