In [19]:
import tensorflow as tf

In [20]:
print(tf.__version__)

1.4.1


In [21]:
hello = tf.constant("Hello ")
world = tf.constant("World")

In [22]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [23]:
print(hello)

Tensor("Const_5:0", shape=(), dtype=string)


In [24]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [25]:
print(result)

b'Hello World'


In [26]:
a = tf.constant(10)
b = tf.constant(20)
type(a)

tensorflow.python.framework.ops.Tensor

In [27]:
a + b 

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [28]:
a + b

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [29]:
a + b

<tf.Tensor 'add_8:0' shape=() dtype=int32>

In [30]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [31]:
result

30

In [32]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),10)

In [33]:
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [34]:
myzeros

<tf.Tensor 'zeros_1:0' shape=(4, 4) dtype=float32>

In [35]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [49]:
#USEFUK FOR JUPYTER NOTEBOOK
sess = tf.InteractiveSession() 
for op in my_ops:
    res = sess.run(op)
    print(res)
    print(10*'-')

10
----------
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------
[[-0.39529732 -0.35704455  0.5733927  -0.05067979]
 [-0.03335493 -0.03677049 -0.46470246  1.6261535 ]
 [ 0.05736826  0.4968466   0.08039705  1.0607055 ]
 [ 0.3210415  -0.99926895 -2.0680506   2.3651977 ]]
----------
[[0.8530127  0.2777456  0.41246688 0.6220043 ]
 [0.19674575 0.9889319  0.99110174 0.32374644]
 [0.93554175 0.19835186 0.4182831  0.8966156 ]
 [0.92430985 0.47990978 0.55261743 0.7607355 ]]
----------


In [40]:
a = tf.constant([ [1,2],
                  [3,4]  ])

In [42]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [43]:
b = tf.constant([[10], [100]])

In [44]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [45]:
result_dot_product = tf.matmul(a,b)

In [46]:
sess.run(result_dot_product)

array([[210],
       [430]], dtype=int32)

In [47]:
result_multiply = tf.multiply(a,b)

In [48]:
sess.run(result_multiply)

array([[ 10,  20],
       [300, 400]], dtype=int32)