In [ ]:
import os
import h5py
import json
import pandas as pd

In [ ]:
import tensorflow as tf

In [ ]:
#a = tf.constant([[100, 110], [10, 20], [1000, 1100]])
a = tf.random_uniform(shape=[3, 150,1024])

In [ ]:
b = tf.reduce_mean(a)
c = tf.reduce_mean(a, axis=0)
d = tf.reduce_mean(a, axis=1)
e = tf.reduce_mean(a, axis=2)
f = tf.reduce_mean(a, axis=[0,1])

In [ ]:
session = tf.Session()

In [ ]:
print("INPUT")
print(session.run(a))
print("REDUCE MEAN")
print(session.run(b))
print("REDUCE MEAN (shape)")
print(b.shape)
print("REDUCE MEAN AXIS 0")
print(session.run(c))
print("REDUCE MEAN AXIS 0 (shape)")
print(c.shape)
print("REDUCE MEAN AXIS 1")
print(session.run(d))
print("REDUCE MEAN AXIS 1 (shape)")
print(d.shape)
print("REDUCE MEAN AXIS 2")
print(session.run(e))
print("REDUCE MEAN AXIS 2 (shape)")
print(e.shape)
print("REDUCE MEAN AXIS 0,1")
print(session.run(f))
print("REDUCE MEAN AXIS 0,1 (shape)")
print(f.shape)

In [ ]:
#dataset_type = 'train'
dataset_type = 'dev'
dataset_version = 'v1.1'

index_field = ['Unnamed: 0']

# required files
_basepath = '/home/jackalhan/Development/github/bilm-tf/squad'
datadir = os.path.join(_basepath, dataset_type)
modeldir = os.path.join(_basepath, 'model')

In [ ]:

filename = 'file.hdf5'
f = h5py.File(filename, 'r')

# List all groups
print("Keys: %s" % f.keys())
a_group_key = list(f.keys())[0]

# Get the data
data = list(f[a_group_key])

In [ ]:
paragraphs_with_mean = []
questions_with_mean = []
items = [dict({'type':'question', 
                     'list':questions_with_mean, 
                     'source_file':embedding_question_file_as_h5py,
                     'destination_file': embedding_mean_question_file_as_h5py}), 
              dict({'type':'paragraph', 
                     'list':paragraphs_with_mean, 
                     'source_file':embedding_paragraph_file_as_h5py,
                     'destination_file': embedding_mean_paragraph_file_as_h5py})
              ]
for vals in items:
    print(vals['type'], 'is getting processed!!!')
    config = tf.ConfigProto(allow_soft_placement=True)
    
    with h5py.File(vals['source_file'], 'r') as fin:
        data_as_array = np.array(fin)
    
    print(data_as_array.shape)
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())
         h5py.File(vals['destination_file'], 'w') as fout:
            #for _ in tqdm_notebook(fin, total=len(fin)):
                mean_vectors = sess.run(tf.reduce_mean(fin[str(_)][...], axis=[0,1]))
                
                data_as_array
                x = tf.placeholder(tf.float32, [100, 250])
                norm = tf.sqrt(tf.reduce_sum(tf.square(x), 1, keep_dims=True))
                res = x / norm
                vals['list'].append(mean_vector)
                ds = fout.create_dataset(
                        '{}'.format(_),
                        mean_vector.shape, dtype='float32',
                        data=mean_vector)

In [11]:
import numpy as np
q = np.empty((0, 8), dtype=float)
q = np.append(q, [[2, 0, 1, 1, 0, 2, 1, 1]], axis=0)

p = np.empty((0, 8), dtype=float)
p = np.append(p, [[7, 5, -23, 0, 1, 1, 1, 1]], axis=0)
p = np.append(p, [[2, 1, 1, 0, 1, 1, 1, 1]], axis=0)
p = np.append(p, [[2, 1, 1, 0, 1, 1, 1, 0]], axis=0)
p = np.append(p, [[2, 0, 1, 1, 0, 2, 1, 1]], axis=0)

In [2]:
from sklearn.metrics.pairwise import cosine_similarity
import scipy.spatial.distance as distance

In [ ]:
results = []
for q_id, _ in enumerate(tqdm_notebook(q, total=len(p))):
    q_vec = np.array([_]) 
    sk_sim = cosine_similarity(q_vec,p)[0]
    actual_paragraph_id = 0 #df_qas[df_qas['Question_Id'] == q_id]['Paragraph_Id'].values[0]
    similarities = np.argsort(-sk_sim)
    print('actual_paragraph_id', actual_paragraph_id)
    print('sk_sim:', sk_sim)
    print('similarities (argsort):', similarities)
    order_of_the_actual_paragraph_id = np.where(similarities == actual_paragraph_id)[0][0] + 1
    print('order_of_the_actual_paragraph_id:', order_of_the_actual_paragraph_id)
    print('score for actual paragraph id:', sk_sim[actual_paragraph_id])
    calculated_most_similar_1_paragraph = similarities[0]
    print('calculated_most_similar_1_paragraph:', calculated_most_similar_1_paragraph)
    print('score for most similar paragraph:', sk_sim[calculated_most_similar_1_paragraph])
    #     results.append((q_id, actual_paragraph_id,  order_of_the_actual_paragraph_id, calculated_most_similar_1_paragraph, sk_sim[calculated_most_similar_1_paragraph]))


In [12]:
q.shape, p.shape

((1, 8), (4, 8))

In [3]:
from sklearn.preprocessing import normalize

In [13]:
p_ = normalize(p, norm='l1', axis=1)
p1_ = p/np.abs(p).sum(axis=1).reshape(3,1)
np.abs(p).sum(axis=1).reshape(3,1)

ValueError: cannot reshape array of size 4 into shape (3,1)

In [17]:
q_ = normalize(q, norm='l1', axis=1)
p_ = normalize(p, norm='l1', axis=1)

In [14]:
p_

array([[ 0.17948718,  0.12820513, -0.58974359,  0.        ,  0.02564103,
         0.02564103,  0.02564103,  0.02564103],
       [ 0.25      ,  0.125     ,  0.125     ,  0.        ,  0.125     ,
         0.125     ,  0.125     ,  0.125     ],
       [ 0.28571429,  0.14285714,  0.14285714,  0.        ,  0.14285714,
         0.14285714,  0.14285714,  0.        ]])

In [18]:
np.dot(q_, p_.T)

array([[-0.01602564,  0.140625  ,  0.14285714,  0.1875    ]])

In [19]:
cosine_similarity(q,p)[0]

array([-0.05858481,  0.82158384,  0.76980036,  1.        ])